---
- name: installing nopcommerce on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install microsoft packages
      ansible.builtin.apt:
        deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    - name: install dotnet core dotnet-runtime
      ansible.builtin.apt:
        update_cache: yes
        pkg: 
          - apt-transport-https
          - aspnetcore-runtime-7.0
          - nginx
          - unzip
        state: present  
    - name: start nginx service
      ansible.builtin.systemd:
        name: nginx
        state: started
    - name: copy the ansible file
      ansible.builtin.copy:
        src: nop-default
        dest: /etc/nginx/sites-available/default 
    - name: create a file
      ansible.builtin.file:
        path: /var/www/nopCommerce
        state: touch
        mode: '0777'  
    - name: dowmload the nopCommerce
      ansible.builtin.get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.2/nopCommerce_4.60.2_NoSource_linux_x64.zip
        dest: /home/sai
        mode: '0777'
    - name: unarchive the nopCommerce file
      ansible.builtin.unarchive:
        src: nopCommerce_4.60.2_NoSource_linux_x64.zip
        dest: /home/sai
        remote_src: yes
    - name: create two files
      ansible.builtin.file:
        path: /var/www/nopCommerce/bin
        state: touch
        mode: '0777'
    - name: create two files
      ansible.builtin.file:
        path: /var/www/nopCommerce/logs
        state: touch
        mode: '0777'     
    - name: create two files
      ansible.builtin.file:
        path: /var/www/nopCommerce/bin
        state: touch
        mode: '0777'    
    - name: change directory
      ansible.builtin.command:
        chdir: /var/www 
    - name: change permissions 
      ansible.builtin.file:
        path: /var/www
        owner: www-data
        group: nopCommerce
        mode: "0777"
    - name: change ownership
      ansible.builtin.file:
        path: /var/www
        owner: www-data
        group: nopCommerce
        mode: "0777"
    - name: copying service file
      ansible.builtin.copy:
        src: nopCommerce.service
        dest: /etc/systemd/system/nopCommerce.service
        owner: nopCommerce
        group: nopCommerce
        mode: "0777"
    - name: deamon reload and restart nopCommerce
      ansible.builtin.systemd:
        name: nopCommerce
        daemon_reload: yes
        state: restart  
    - name: restart nginx service
      ansible.builtin.systemd:
        name: nginx
        state: restarted        

                     

          


