---
- name: install LAMP in ubuntu
  become: yes
  hosts: all
  tasks:
    - name: insatll apache2 
      apt:
        name: apache2
        state: present
        update_cache: yes  
    - name: install PHP
      apt:
      name: 
        - php 
        - libapache2-mod-php 
        - php-mysql
        state: present
    - name: copy the info.php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
        remote_src: yes
    - name: ensure the apache service is running and enabled
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        state: started
