---
- name: install oenjdk-17-jdk
  hosts: all
  become: yes
  tasks:
    - name: install openjdk-17-jdk
      ansible-builtin.apt:
        name: openjdk-17-jdk
        update_cache: yes
        state: present