---
- name: installing dotnet on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: downloding microsoft packages
      ansible.builtin.apt:
        deb: https://packages.microsoft.com/config/ubuntu/22.10/packages-microsoft-prod.deb
    - name: istalling aspcore-sdk-7.0
      ansible.builtin.apt:
        pkg:
          - dotnet-sdk-7.0
          - aspnetcore-runtime-7.0
          - dotnet-runtime-7.0
        update_cache: yes
        state: present
   

        