---
- name: installing dotnet on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: downloding microsoft packages
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/22.10/packages-microsoft-prod.deb 
        dest: /home/ubuntu
    - name: installing packages
      ansible.builtin.dpkg_selections:
        name: packages-microsoft-prod.deb
        selection: install
    - name: istalling aspcore-sdk-7.0
      ansible.builtin.apt:
        name: dotnet-sdk-7.0
        update_cache: yes
        state: present
    - name: installing dotnet runtime        
      ansible.builtin.apt:
        name: aspnetcore-runtime-7.0
        update_cache: yes
        state: present
    - name: installing dotnet-runtime-7.0 
      ansible.builtin.apt:
        name: dotnet-runtime-7.0
        update_cache: yes
        state: present

        