---
- name: installing java
  hosts: all
  become: yes
  vars:
    java_packege: openjdk-11-jdk
  tasks:
    - name: install java
      ansible.builtin.apt:
        name: "{{ java_packege }}"
        update_cache: yes
        state: present
      notify:
        - installed java  
  handlers:
    - name: installed java
      ansible.builtin.debug:
        var: installing java      