---
- name: install utilites
  hosts: all
  become: yes
  vars:
    utils:
      - nano
      - tree 
      - git
  tasks:
    - name: install utilites
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      notify:
        - printmy msg
  handlers:
    - name: printmy msg
      ansible.builtin.debug:
        msg: instaling varibles      
